export { default as Navbar } from './navbar/Navbar'
export { default as About } from './about/About'
export { default as Gallery } from './gallery/Gallery'
export { default as Footer } from './footer/Footer'
export { default as ContactForm } from './contactForm/ContactForm'
export { default as BackgroundImage } from './backgroundImage/BackgroundImage'
export { default as Testimonials } from './testimonials/Testimonials'
export { default as Features } from './features/Features'
export {default as ScrollTrigger} from './scrolltrigger/ScrollTrigger'