export {default as Navbar} from './navbar/Navbar'
export { default as Hero } from './hero/Hero'
export { default as About } from './about/About'
export { default as Gallery } from './gallery/Gallery'
export {default as Footer} from './footer/Footer'